title: Test Just the Docs
description: Testing Just the Docs theme!
theme: just-the-docs

url: https://rensgitx.github.io/dumpster-dive

aux_links:
  Template Repository: https://github.com/rensgitx/dumpster-dive
